# === Build stage ===
FROM gradle:8.7-jdk21 AS build
WORKDIR /home/gradle/project

COPY . .

RUN gradle clean build -x test --no-daemon

# === Run stage ===
FROM eclipse-temurin:21-jre
WORKDIR /app

COPY --from=build /home/gradle/project/build/libs/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
